site_name: vQTL
site_description: vQTL Project Documentation
repo_url: https://github.com/AustinGratton/vQTL/vQTL_Project/doc_files
theme: readthedocs
edit_uri: https://github.com/AustinGratton/vQTL/vQTL_Project/doc_files
site_dir: '../site/'
docs_dir: /docs
pages:
- 'Home': index.md
- 'Project Overview': Project_Overview.md
- WorkFlow:
    - 'Getting Started': 'workflow/Using_R.md'
    - 'Data': 'workflow/Data.md'
    - 'vQTL Analysis': 'workflow/vQTL_Analysis.md'
    - 'qPCR Analysis': 'workflow/qPCR_Analysis.md'
    - 'Workflow': 'workflow/Workflow.md'
- Tutorials:
    - 'Getting Started With High Performance Computing': 'tutorials/Using_HPC.md'
    - 'Introduction to GitHub and Project Set-up': 'tutorials/Using_GitHub.md'
    - 'Jobs on HPC': 'tutorials/Jobs_on_HPC.md'
    - 'Launcher Module': 'tutorials/Launcher_Module.md'
    - 'Reminders and Useful Commands': 'tutorials/Reminders_and_Useful_Commands.md'
    - 'Updating the Docs': 'tutorials/Updating_the_Docs.md'


site_author: 'Austin Gratton and Michael Copeland'
